### ISSUE TITLE
Cannot read "concat" property of schemaPath variable

### ISSUE THREAD

**Issue by pralatto** [mafintosh/is-my-json-valid#153]
When I tried to execute the newest version of eslint-changes on travis

```
./node_modules/.bin/eslint-changes
/home/travis/build/project/node_modules/is-my-json-valid/index.js:366
      visit(name+'['+i+']', node.items, reporter, filter, schemaPath.concat('items'))
                                                                     ^
      TypeError: Cannot read property 'concat' of undefined
    at visit (/home/travis/build/project/node_modules/is-my-json-valid/index.js:366:70)
    at /home/travis/build/project/node_modules/is-my-json-valid/index.js:416:9
    at Array.forEach (<anonymous>)
    at visit (/home/travis/build/project/node_modules/is-my-json-valid/index.js:409:18)
    at /home/travis/build/project/node_modules/is-my-json-valid/index.js:543:9
    at Array.forEach (<anonymous>)
    at visit (/home/travis/build/project/node_modules/is-my-json-valid/index.js:540:31)
    at compile (/home/travis/build/project/node_modules/is-my-json-valid/index.js:565:3)
    at visit (/home/travis/build/project/node_modules/is-my-json-valid/index.js:340:16)
    at /home/travis/build/project/node_modules/is-my-json-valid/index.js:416:9
```

**Comment by LinusU** [comment]
Hello, this was an error in version `2.17.0` and has now been fixed in `2.17.1`, see #149 for more details. Sorry for any inconvenience.
