### ISSUE TITLE
ERROR: Cannot read property 'concat' of undefined

### ISSUE THREAD

**Issue by chrisrink** [mafintosh/is-my-json-valid#156]
I saw this error when running eslint(4.1.1). This just happened So I think this had to do with the recent bump to 2.17

```
FO] TypeError: Cannot read property 'concat' of undefined
06:40:46  [INFO]     at visit (MyModule/node_modules/is-my-json-valid/index.js:366:69)
06:40:46  [INFO]     at /MyModule/node_modules/is-my-json-valid/index.js:435:9
06:40:46  [INFO]     at Array.forEach (native)
06:40:46  [INFO]     at visit (MyModule/UIPlatform/node_modules/is-my-json-valid/index.js:434:18)
06:40:46  [INFO]     at MyModule/node_modules/is-my-json-valid/index.js:543:9
06:40:46  [INFO]     at Array.forEach (native)
06:40:46  [INFO]     at visit (MyModule/node_modules/is-my-json-valid/index.js:540:31)
06:40:46  [INFO]     at visit (MyModule/node_modules/is-my-json-valid/index.js:366:7)
06:40:46  [INFO]     atMyModule/node_modules/is-my-json-valid/index.js:543:9
06:40:46  [INFO]     at Array.forEach (native)
06:40:46  [ERROR] 
```

**Comment by chrisrink** [comment]
Looks like this is fixed in 2.17.1 per https://github.com/mafintosh/is-my-json-valid/issues/155 and my local testing.
