### ISSUE TITLE
ESLINT uses "is-my-json-valid" and schemaPath.concat() cannot read property

### ISSUE THREAD

**Issue by antoxas1986** [mafintosh/is-my-json-valid#157]
Hello,

I have your package used by eslint package, and now I have an error when trying do ''gulp eslint"

eslint: 3.19.0
is-my-json-valid: 2.17.1

 visit(name+'['+i+']', node.items, reporter, filter, schemaPath.concat('items'))
                                                                    ^

TypeError: Cannot read property 'concat' of undefined
    at visit (/var/lib/jenkins/workspace/PerModuleReleasePipeline/aop-tactic-workflow/node_modules/is-my-json-valid/index.js:366:69)
    at /var/lib/jenkins/workspace/PerModuleReleasePipeline/aop-tactic-workflow/node_modules/is-my-json-valid/index.js:416:9
    at Array.forEach (native)
    at visit (/var/lib/jenkins/workspace/PerModuleReleasePipeline/aop-tactic-workflow/node_modules/is-my-json-valid/index.js:409:18)
    at /var/lib/jenkins/workspace/PerModuleReleasePipeline/aop-tactic-workflow/node_modules/is-my-json-valid/index.js:543:9
    at Array.forEach (native)
    at visit (/var/lib/jenkins/workspace/PerModuleReleasePipeline/aop-tactic-workflow/node_modules/is-my-json-valid/index.js:540:31)
    at compile (/var/lib/jenkins/workspace/PerModuleReleasePipeline/aop-tactic-workflow/node_modules/is-my-json-valid/index.js:565:3)
    at visit (/var/lib/jenkins/workspace/PerModuleReleasePipeline/aop-tactic-workflow/node_modules/is-my-json-valid/index.js:340:16)
    at /var/lib/jenkins/workspace/PerModuleReleasePipeline/aop-tactic-workflow/node_modules/is-my-json-valid/index.js:416:9

Have to downgrade "is-my-json-valid" version to 2.16.1.

Please check your change with eslint package

**Comment by LinusU** [comment]
Hello, this was an error in version `2.17.0` and has now been fixed in `2.17.1`, see #149 for more details. Sorry for any inconvenience.
